# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenInteract2-Action-FlickrFeed
version:      0.01
version_from: lib/OpenInteract2/Action/FlickrFeed.pm
installdirs:  site
requires:
    OpenInteract2::Action::RSS:    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
